### ISSUE TITLE
Extend package manager client to be able to store extensions.

### ISSUE THREAD

**Issue by ikeough** [DynamoDS/PackageManagerClient#11]
The package manager should be an extensibility mechanism for both packages _and_ extensions. We should add an `/extensions` folder to the package structure, and adapt the dynamo extensions framework to search for `/extensions` folders in packages to load extensions.

**Comment by ramramps** [comment]
@ikeough - Globiant is working on package manager project. I think they are working on Dynamo as well connecting to the latest back end. Does this affect their process?

**Comment by ikeough** [comment]
@ramramps I don't know the scope of their work, so I can't say for sure. My understanding from @kronz is that they are currently working on improvements to the PM UI and a prototype back-end, and that all of this work is being done in a separate branch. If we want this, we should add it, and discuss with them how to adapt their work to fit.

Is there documentation for their scope of work somewhere?

**Comment by ramramps** [comment]
I dont have the documentation.They are working on the backend and UI. But I am not sure whether they are working on Dynamo. I will check.

**Comment by erfajo** [comment]
Why is their a limitation on the root folder structure in a package?
In my package is all Python coding kept outside the nodes as py files. Those files are not "bin" files, they are "lib" files (Python phrase). For now have I made a "lib" folder in the "extra" folder, since that was the the least bad choice.

**Comment by mjkkirschner** [comment]
closing this as the original request was implemented though in a different way than suggested.
