### ISSUE TITLE
remove/rename old packages and remove versions

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/PackageManagerClient#17]
Why can't I as the package manager pull packages of the package site?

My first package years ago was named "Door Ironmongery", but that was of cause totally stupid. I found out to my great fear that I couldn't rename that package. Why is that so really? It's too crazy that it is not allowed.

It ended up making a new package and moved the one node in the previous package to the new package. The old package has been present for years now, and that is simply stupid.
Likewise goes for versions there had errors, I have a handful of version there should be totally removed so no one risk to download them.

I cant understand why it isn't mee there can decide how I want my things to be present in the dynamo environment. At GitHub is it me there can remove a repo if I want to do that, and the same goes for renaming.

My current package is named ”DanEDU Dynamo” but I would like to follow the name convention others hold, meaning ”DanEDU for Dynamo” would be the new name.

Please make everything much more driven by the package manager and not the ”system”.

**Comment by ramramps** [comment]
Thanks @erfajo. We have Package Manager projects / enhancements in the roadmap. We will certainly address this. In the mean time, we will see whether this package can be removed in the back end.

**Comment by kronz** [comment]
@erfajo We will take it down if you like. In the meantime, any reason you have not deprecated it?

**Comment by erfajo** [comment]
@ramramps @kronz 
Please take "Door Ironmongery" down. The package has also been set as deprecated for the same amount of years. Deprecated doesn't mean that it disappears unfortunately.

What about removing/deleting versions?
What about renaming packages?

**Comment by kronz** [comment]
Hi @erfajo 
Understood, we are working on a Delete operation seperate from Deprecate.  What I'm wondering about though is if there is a reason your package isn't actually set as deprecated:
![2018-01-08_0908](https://user-images.githubusercontent.com/3456818/34674492-1b564864-f454-11e7-91ea-c7d0e5a035b8.png)

![2018-01-08_0910](https://user-images.githubusercontent.com/3456818/34674500-21f267ac-f454-11e7-97d6-0d026ec591a0.png)

If it was deprecated it would indicate it here:
![2018-01-08_0914](https://user-images.githubusercontent.com/3456818/34674561-6dc7f480-f454-11e7-90f4-47caa9d0c3cf.png)

**Comment by erfajo** [comment]
@kronz 
That's strange, I am sure I deprecated it years ago. Sorry, I didn't check other packages so I knew that I could check that it actually was deprecated.

If I could have renamed my package back then, then this would not have been a problem at all. Why can't we rename packages? 

Why not implement a guid, so we don't have a technical problem in renaming. Combined with if the new name for a package doesn't exist in advance, then any name should be acceptable to rename a package into.

In the same ball game, have I asked for version numbering in another post. Why check on the version number must be higher than the previous, why not check if the number exists in advance, if not, then any number should be acceptable.

**Comment by erfajo** [comment]
After a while, I ended deprecating my second package since the renaming issue didn't look to be solved at all. Result is that I now have two deprecated packages I want to remove from the package site.

Could you please delete both “DanEDU” and “Door Ironmongery” packages?
![snap000130](https://user-images.githubusercontent.com/2844374/39582673-bceb0e90-4eee-11e8-865c-d170f343b07e.png)

Version numbering is also a problem... Now where we have Dynamo 2.0 is it impossible to release a package 1.3 and a package 2.0 parallel to each other. Version numbers must be higher for every release!?

I hope that it will be possible to host packages with a link to github some day. That way can we, as authors, descide what we want to do and how we will maintain it.

**Comment by ramramps** [comment]
@kronz Please advice on this..should we really wanted to delete this package?

**Comment by erfajo** [comment]
I have reused the same nodes, meaning the same guid for the custom nodes that not are being replaced by zerotouch nodes. which is most of them.

As an author is it really problematic, that I don't have the control to delete my own nodes... I can delete a GitHub project!?

**Comment by kronz** [comment]
Hey Erik, 
Can you send an email from the account that you are using to sign in to the package manager to Dynamo@autodesk.com with the request to takedown?
Thanks
Zach

**Comment by erfajo** [comment]
done, sent from my gmail account...

**Comment by erfajo** [comment]
I have just tested, and it seems like they are still there!?

**Comment by ramramps** [comment]
@erfajo It is not removed yet. We will send a notification once it is removed.

**Comment by ramramps** [comment]
@erfajo These two packages are removed from our Database.

**Comment by erfajo** [comment]
@ramramps thanks a lot. 
In the meantime have I also found a way so I can maintain two different parallels of the same package, one for dynamo +1.3.0 and one for dynamo +2.0.0 series. As you know, +1.3.0 supports up to dotNET 4.6 and +2.0.0 supports dotNET 4.7.
It is not possible to maintain two parallels in the current settings at the package site if you want to have the same package name!

So I would also like you to remove my Orchid package. I will upload what is needed for having the placeholder package name afterwards.

Here is more info if needed...
https://forum.dynamobim.com/t/search-in-dynamo-revit-is-painfully-slow/11029/17

**Comment by erfajo** [comment]
yes, thats it

**Comment by ramramps** [comment]
Thanks @erfajo..confirming one more time, this is package is not deprecated...
I will delete this package if I don't see any objection in a day or so.

**Comment by erfajo** [comment]
it is the Orchid package I want removed... so I can take control over it. Thanks

**Comment by ramramps** [comment]
It's done.

**Comment by erfajo** [comment]
Thanks.
It works perfectly, and I have made new placeholder packages.

I hope that the package manage one day will be made doable for renaming, renumbering and parallel versions. Until that is fixed will I release and maintain my packages from Github.

You may close the issue and mark it as solved :-)

**Comment by ramramps** [comment]
Thanks @erfajo
